//
//  AppController.m
//  BioVizCorePlot18
//
//  Created by Rick Schmidt on 3/8/10.
//  Copyright 2010 __MyCompanyName__. All rights reserved.
//

#import "AppController.h"


@implementation AppController

-(IBAction)blastWithBlastcl3:(id)sender{
	Blast *blastControl;
	blastControl=[[Blast alloc]init];
	NSInteger i=5;
	NSArray *inputSeqs;
	inputSeqs=[self csvSplit];
	//[blastControl blast:i];
	[blastControl blastMany:inputSeqs];
}
-(IBAction )xmlStuff:(id)sender
{
	XMLParser *xmlStuff;
	xmlStuff=[[XMLParser alloc]init];
	[xmlStuff initXML];
	[xmlStuff getArrayForNode:@".//Hit_id"];
}
-(NSArray *)csvSplit
{
	//	NSString *returnValue=[csvInputField stringValue];
	//NSString *returnValue=@"CAGTGAATTCGAGCTCGGTACCCGGGGATCCTCTAGAGGGTTCTTAGAATTAAGTATTAGACAAAAAAGAAAATTTGATTCTTGGAAAAGATTATCAGAATTATATGAAAATCCAATTGTTATGTCACCATATTTATATAATAATTGTATAAGACAAGGTTTTGTTGCGGATTGTTCTTTTCTGTCTTCATTAACAGTATTAATAGAATATGAGAAAAAACATAAGATACCTGTTATTTCTAGTATTATAACACCTTGTAGTTGGAATTATTTATGTATAAATAAAACGTGGCCTATTTTTAATCCTTGTGGTATGTATATATGTAGACTTCATTGTAATGGTATACAAAGAAAGATAATAATAGATGATTATGTACCGGTTAAGAACAATAATTCATTGCTTGTGGCTTATTCAAATAATCAAAAAGAATTATGGGTTACCTTATTAGAAAAAGCTTTTGTTAAATTGATGGGAGGATCATATTCTATGTTTGGTTCTAATCCTGGTTCTGATTTGTATTATTTGACAGGTTGGATACCAGTAACCATATCTTTGAAATCTAAGATTAGTAGTTCTCCCCCTTCTTTTGACAAACATAGTACGCATTCTTTAATAAGGGATGAGCGTATAGATGAATGGNATATGAAACTAACGAGGTAATGATAAATAAGAAACATGGATATGTTACAGTGTTGAATTTGTAGAGGACCCAAAGTATAATCATATTATTATTATTATTATTATTTAAAATAATCGGAACTTGATCCAAATTGTGTGAAGATTAATTTGTTAAAATATACA,AATTCGAGCTCGGTACCCGGGGATCCTCTAGAGGGTTCTTAGAATTAAGTATTAGACAAAAAAGAAAATTTGATTCTTGGAAAAGATTATCAGAATTATATGAAAATCCAATTGTTATGTCACCATATTTATATAATAATTGTATAAGACAAGGTTTTGTTGCGGATTGTTCTTTTCTGTCTTCATTAACAGTATTAATAGAATATGAGAAAAAACATAAGATACCTGTTATTTCTAGTATTATAACACCTTGTAGTTGGAATTATTTATGTATAAATAAAACGTGGCCTATTTTTAATCCTTGTGGTATGTATATATGTAGACTTCATTGTAATGGTATACAAAGAAAGATAATAATAGATGATTATGTACCGGTTAAGAACAATAATTCATTGCTTGTGGCTTATTCAAATAATCAAAAAGAATTATGGGTTACCTTATTAGAAAAAGCTTTTGTTAAATTGATGGGAGGATCATATTCTATGTTTGGTTCTAATCCTGGTTCTGATTTGTATTATTTGACAGGTTGGATACCAGTAACCATATCTTTGAAATCTAAGATTAGTAGTTCTCCCCCTTCTTTTGACAAACATAGTACGCATTCTTTAATAAGGGATGAGCGTATAGATGAATGGNATATGAAACTAACGAGGTAATGATAAATAAGAAACATGGATATGTTACAGTGTTGAATTTGTAGAGGACCCAAAGTATAATCATATTATTATTATTATTATTATTTAAAATAATCGGAACTTGATCCAAATTGTGTGAAGATTAATTTGTTAAAATATACA";
	//NSString *returnValue=[[NSString alloc]init];
	//returnValue=[csvInputTextBox stringValue];
	//NSString *returnValue=@"GU134730.1,CAGTGAATTCGAGCTCGGTACCCGGGGATCCTCTAGAGGGTTCTTAGAATTAAGTATTAGACAAAAAAGAAAATTTGATTCTTGGAAAAGATTATCAGAATTATATGAAAATCCAATTGTTATGTCACCATATTTATATAATAATTGTATAAGACAAGGTTTTGTTGCGGATTGTTCTTTTCTGTCTTCATTAACAGTATTAATAGAATATGAGAAAAAACATAAGATACCTGTTATTTCTAGTATTATAACACCTTGTAGTTGGAATTATTTATGTATAAATAAAACGTGGCCTATTTTTAATCCTTGTGGTATGTATATATGTAGACTTCATTGTAATGGTATACAAAGAAAGATAATAATAGATGATTATGTACCGGTTAAGAACAATAATTCATTGCTTGTGGCTTATTCAAATAATCAAAAAGAATTATGGGTTACCTTATTAGAAAAAGCTTTTGTTAAATTGATGGGAGGATCATATTCTATGTTTGGTTCTAATCCTGGTTCTGATTTGTATTATTTGACAGGTTGGATACCAGTAACCATATCTTTGAAATCTAAGATTAGTAGTTCTCCCCCTTCTTTTGACAAACATAGTACGCATTCTTTAATAAGGGATGAGCGTATAGATGAATGGNATATGAAACTAACGAGGTAATGATAAATAAGAAACATGGATATGTTACAGTGTTGAATTTGTAGAGGACCCAAAGTATAATCATATTATTATTATTATTATTATTTAAAATAATCGGAACTTGATCCAAATTGTGTGAAGATTAATTTGTTAAAATATACA";
	NSString *returnValue;
	
	
	returnValue=[csvInputTextBox stringValue];
	NSLog(@"return value %@",returnValue);
	NSScanner *scanner=[[NSScanner alloc]init];
	scanner=[NSScanner scannerWithString:returnValue];
	NSCharacterSet *characterSet=[NSCharacterSet characterSetWithCharactersInString:@","];
	
	NSArray *array;  //=[[NSArray alloc]init];
	
	
	array=[returnValue componentsSeparatedByCharactersInSet:characterSet];
	int j=[array count];
	int i=0;
	while (i<j) {
		
	
		NSLog(@"array object %@", [array objectAtIndex:i]);		
		i++;
	}
	return array;
}	
@end
